from typing import Protocol, runtime_checkable
import numpy as np

@runtime_checkable
class ClassifierProtocol(Protocol):
    def fit(self, X: np.ndarray, y: np.ndarray) -> "ClassifierProtocol": ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, X:np.ndarray) -> np.ndarray: ...
    def score(self, X: np.ndarray) -> float: ...